# TODO: Consult with Michael Twelkemeier - not working !
FROM openjdk:8-alpine

RUN addgroup -g 1000 -S appuser && adduser -u 1000 -S appuser -G appuser

ADD camunda-kafka-polling-client/target/camunda-kafka-polling-client.jar app.jar

USER appuser

ENTRYPOINT ["java", "-jar", "/app.jar"]