FROM openjdk:8-alpine

RUN addgroup -g 1000 -S appuser && \
    adduser -u 1000 -S appuser -G appuser && \
    mkdir -p /data

ADD camunda-kafka-polling-client/target/camunda-kafka-polling-client.jar app.jar

RUN chown -R appuser:appuser /data && \
    chmod 770 /data

VOLUME /data

USER appuser

ENTRYPOINT ["java", "-jar", "/app.jar"]