# TODO: Consult with Michael Twelkemeier   - working
FROM openjdk:8-alpine

RUN addgroup -g 1000 -S appuser && \
    adduser -u 1000 -S appuser -G appuser && \
    mkdir -p /app && \
    mkdir -p /data

#ARG APP_COMPONENT_DIR=camunda-kafka-polling-client/target/dependency   # TODO: check if necessary: result: not necessary

#COPY ${APP_COMPONENT_DIR}/BOOT-INF/lib /app/lib          # TODO: check if necessary: result: not necessary
#COPY ${APP_COMPONENT_DIR}/BOOT-INF/classes /app/bin      # TODO: check if necessary: result: not necessary
#COPY ${APP_COMPONENT_DIR}/META-INF /app/bin/META-INF     # TODO: check if necessary: result: not necessary

ADD camunda-kafka-polling-client/target/camunda-kafka-polling-client.jar app.jar

RUN chown -R appuser:appuser /app && \
    chown -R appuser:appuser /data && \
    find /app -type d -exec chmod 550 {} + && \
    find /app -type f -exec chmod 660 {} + && \
    chmod 770 /data

VOLUME /data
USER appuser

ENTRYPOINT ["java", "-jar", "/app.jar"]