// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
import java.util.Map;

/**
 * Response structure of Camunda REST API <code>GET /history/decision-instance</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetHistoricDecisionInstanceInputResponse {

    private String id;
    private String decisionInstanceId;
    private String clauseId;
    private String clauseName;
    private String errorMessage;
    private String type;
    private Date createTime;
    private Date removalTime;
    private String rootProcessInstanceId;
    private String value;
    private Map<String, Object> valueInfo;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDecisionInstanceId() {
        return decisionInstanceId;
    }

    public void setDecisionInstanceId(String decisionInstanceId) {
        this.decisionInstanceId = decisionInstanceId;
    }

    public String getClauseId() {
        return clauseId;
    }

    public void setClauseId(String clauseId) {
        this.clauseId = clauseId;
    }

    public String getClauseName() {
        return clauseName;
    }

    public void setClauseName(String clauseName) {
        this.clauseName = clauseName;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getRemovalTime() {
        return removalTime;
    }

    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }

    public String getRootProcessInstanceId() {
        return rootProcessInstanceId;
    }

    public void setRootProcessInstanceId(String rootProcessInstanceId) {
        this.rootProcessInstanceId = rootProcessInstanceId;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Map<String, Object> getValueInfo() {
        return valueInfo;
    }

    public void setValueInfo(Map<String, Object> valueInfo) {
        this.valueInfo = valueInfo;
    }

    @Override
    public String toString() {
        return "GetHistoricDecisionInstanceInputResponse{" +
                "id='" + id + '\'' +
                ", decisionInstanceId='" + decisionInstanceId + '\'' +
                ", clauseId='" + clauseId + '\'' +
                ", clauseName='" + clauseName + '\'' +
                ", errorMessage='" + errorMessage + '\'' +
                ", type='" + type + '\'' +
                ", createTime='" + createTime + '\'' +
                ", removalTime='" + removalTime + '\'' +
                ", rootProcessInstanceId='" + rootProcessInstanceId + '\'' +
                ", value='" + value + '\'' +
                '}';
    }
}
