// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;

/**
 * Response structure of Camunda REST API <code>GET /history/activity-instance</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetHistoricActivityInstanceRespone {

    private String id;
    private String parentActivityInstanceId;
    private String activityId;
    private String activityName;
    private String activityType;
    private String processDefinitionKey;
    private String processDefinitionId;
    private String processInstanceId;
    private String executionId;
    private String taskId;
    private String assignee;
    private String calledProcessInstanceId;
    private String calledCaseInstanceId;
    private Date startTime;
    private Date endTime;
    private Long durationInMillis;
    private Boolean canceled;
    private Boolean completeScope;
    private String tenantId;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getParentActivityInstanceId() {
        return this.parentActivityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getActivityId() {
        return this.activityId;
    }

    @java.lang.SuppressWarnings("all")
    public String getActivityName() {
        return this.activityName;
    }

    @java.lang.SuppressWarnings("all")
    public String getActivityType() {
        return this.activityType;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionKey() {
        return this.processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getExecutionId() {
        return this.executionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTaskId() {
        return this.taskId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAssignee() {
        return this.assignee;
    }

    @java.lang.SuppressWarnings("all")
    public String getCalledProcessInstanceId() {
        return this.calledProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCalledCaseInstanceId() {
        return this.calledCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public Date getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDurationInMillis() {
        return this.durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCanceled() {
        return this.canceled;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCompleteScope() {
        return this.completeScope;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setParentActivityInstanceId(final String parentActivityInstanceId) {
        this.parentActivityInstanceId = parentActivityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setActivityId(final String activityId) {
        this.activityId = activityId;
    }

    @java.lang.SuppressWarnings("all")
    public void setActivityName(final String activityName) {
        this.activityName = activityName;
    }

    @java.lang.SuppressWarnings("all")
    public void setActivityType(final String activityType) {
        this.activityType = activityType;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionKey(final String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionId(final String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessInstanceId(final String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setExecutionId(final String executionId) {
        this.executionId = executionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTaskId(final String taskId) {
        this.taskId = taskId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAssignee(final String assignee) {
        this.assignee = assignee;
    }

    @java.lang.SuppressWarnings("all")
    public void setCalledProcessInstanceId(final String calledProcessInstanceId) {
        this.calledProcessInstanceId = calledProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCalledCaseInstanceId(final String calledCaseInstanceId) {
        this.calledCaseInstanceId = calledCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartTime(final Date startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndTime(final Date endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setDurationInMillis(final Long durationInMillis) {
        this.durationInMillis = durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public void setCanceled(final Boolean canceled) {
        this.canceled = canceled;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompleteScope(final Boolean completeScope) {
        this.completeScope = completeScope;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "GetHistoricActivityInstanceRespone(id=" + this.getId() + ", parentActivityInstanceId="
                + this.getParentActivityInstanceId() + ", activityId=" + this.getActivityId() + ", activityName="
                + this.getActivityName() + ", activityType=" + this.getActivityType() + ", processDefinitionKey="
                + this.getProcessDefinitionKey() + ", processDefinitionId=" + this.getProcessDefinitionId()
                + ", processInstanceId=" + this.getProcessInstanceId() + ", executionId=" + this.getExecutionId()
                + ", taskId=" + this.getTaskId() + ", assignee=" + this.getAssignee() + ", calledProcessInstanceId="
                + this.getCalledProcessInstanceId() + ", calledCaseInstanceId=" + this.getCalledCaseInstanceId()
                + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ", durationInMillis="
                + this.getDurationInMillis() + ", canceled=" + this.getCanceled() + ", completeScope="
                + this.getCompleteScope() + ", tenantId=" + this.getTenantId() + ")";
    }
}
