// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;

/**
 * Response structure of Camunda REST API <code>GET /history/process-instance</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetHistoricProcessInstanceResponse {

    private String id;
    private String superProcessInstanceId;
    private String superCaseInstanceId;
    private String caseInstanceId;
    private String processDefinitionName;
    private String processDefinitionKey;
    private Integer processDefinitionVersion;
    private String processDefinitionId;
    private String businessKey;
    private Date startTime;
    private Date endTime;
    private Long durationInMillis;
    private String startUserId;
    private String startActivityId;
    private String deleteReason;
    private String tenantId;
    private String state;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getSuperProcessInstanceId() {
        return this.superProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSuperCaseInstanceId() {
        return this.superCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseInstanceId() {
        return this.caseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionName() {
        return this.processDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionKey() {
        return this.processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getProcessDefinitionVersion() {
        return this.processDefinitionVersion;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusinessKey() {
        return this.businessKey;
    }

    @java.lang.SuppressWarnings("all")
    public Date getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDurationInMillis() {
        return this.durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartUserId() {
        return this.startUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartActivityId() {
        return this.startActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeleteReason() {
        return this.deleteReason;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuperProcessInstanceId(final String superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuperCaseInstanceId(final String superCaseInstanceId) {
        this.superCaseInstanceId = superCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseInstanceId(final String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionName(final String processDefinitionName) {
        this.processDefinitionName = processDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionKey(final String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionVersion(final Integer processDefinitionVersion) {
        this.processDefinitionVersion = processDefinitionVersion;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionId(final String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setBusinessKey(final String businessKey) {
        this.businessKey = businessKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartTime(final Date startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndTime(final Date endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setDurationInMillis(final Long durationInMillis) {
        this.durationInMillis = durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartUserId(final String startUserId) {
        this.startUserId = startUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartActivityId(final String startActivityId) {
        this.startActivityId = startActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeleteReason(final String deleteReason) {
        this.deleteReason = deleteReason;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "GetHistoricProcessInstanceResponse(id=" + this.getId() + ", superProcessInstanceId="
                + this.getSuperProcessInstanceId() + ", superCaseInstanceId=" + this.getSuperCaseInstanceId()
                + ", caseInstanceId=" + this.getCaseInstanceId() + ", processDefinitionName="
                + this.getProcessDefinitionName() + ", processDefinitionKey=" + this.getProcessDefinitionKey()
                + ", processDefinitionVersion=" + this.getProcessDefinitionVersion() + ", processDefinitionId="
                + this.getProcessDefinitionId() + ", businessKey=" + this.getBusinessKey() + ", startTime="
                + this.getStartTime() + ", endTime=" + this.getEndTime() + ", durationInMillis="
                + this.getDurationInMillis() + ", startUserId=" + this.getStartUserId() + ", startActivityId="
                + this.getStartActivityId() + ", deleteReason=" + this.getDeleteReason() + ", tenantId="
                + this.getTenantId() + ", state=" + this.getState() + ")";
    }
}
