// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
import java.util.List;

/**
 * Response structure of Camunda REST API <code>GET /history/decision-instance</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetHistoricDecisionInstanceResponse {

    private String id;
    private String decisionDefinitionId;
    private String decisionDefinitionKey;
    private String decisionDefinitionName;
    private String evaluationTime;
    private String removalTime;
    private String processDefinitionId;
    private String processDefinitionKey;
    private String processInstanceId;
    private String caseDefinitionId;
    private String caseDefinitionKey;
    private String caseInstanceId;
    private String activityId;
    private String activityInstanceId;
    private String tenantId;
    private String userId;
    private List<GetHistoricDecisionInstanceInputResponse> inputs;
    private List<GetHistoricDecisionInstanceOutputResponse> outputs;
    private String collectResultValue;
    private String rootDecisionInstanceId;
    private String rootProcessInstanceId;
    private String decisionRequirementsDefinitionId;
    private String decisionRequirementsDefinitionKey;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDecisionDefinitionId() {
        return decisionDefinitionId;
    }

    public void setDecisionDefinitionId(String decisionDefinitionId) {
        this.decisionDefinitionId = decisionDefinitionId;
    }

    public String getDecisionDefinitionKey() {
        return decisionDefinitionKey;
    }

    public void setDecisionDefinitionKey(String decisionDefinitionKey) {
        this.decisionDefinitionKey = decisionDefinitionKey;
    }

    public String getDecisionDefinitionName() {
        return decisionDefinitionName;
    }

    public void setDecisionDefinitionName(String decisionDefinitionName) {
        this.decisionDefinitionName = decisionDefinitionName;
    }

    public String getEvaluationTime() {
        return evaluationTime;
    }

    public void setEvaluationTime(String evaluationTime) {
        this.evaluationTime = evaluationTime;
    }

    public String getRemovalTime() {
        return removalTime;
    }

    public void setRemovalTime(String removalTime) {
        this.removalTime = removalTime;
    }

    public String getProcessDefinitionId() {
        return processDefinitionId;
    }

    public void setProcessDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    public String getProcessDefinitionKey() {
        return processDefinitionKey;
    }

    public void setProcessDefinitionKey(String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    public String getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getCaseDefinitionId() {
        return caseDefinitionId;
    }

    public void setCaseDefinitionId(String caseDefinitionId) {
        this.caseDefinitionId = caseDefinitionId;
    }

    public String getCaseDefinitionKey() {
        return caseDefinitionKey;
    }

    public void setCaseDefinitionKey(String caseDefinitionKey) {
        this.caseDefinitionKey = caseDefinitionKey;
    }

    public String getCaseInstanceId() {
        return caseInstanceId;
    }

    public void setCaseInstanceId(String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
    }

    public String getActivityId() {
        return activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getActivityInstanceId() {
        return activityInstanceId;
    }

    public void setActivityInstanceId(String activityInstanceId) {
        this.activityInstanceId = activityInstanceId;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public List<GetHistoricDecisionInstanceInputResponse> getInputs() {
        return inputs;
    }

    public void setInputs(List<GetHistoricDecisionInstanceInputResponse> inputs) {
        this.inputs = inputs;
    }

    public List<GetHistoricDecisionInstanceOutputResponse> getOutputs() {
        return outputs;
    }

    public void setOutputs(List<GetHistoricDecisionInstanceOutputResponse> ouputs) {
        this.outputs = ouputs;
    }

    public String getCollectResultValue() {
        return collectResultValue;
    }

    public void setCollectResultValue(String collectResultValue) {
        this.collectResultValue = collectResultValue;
    }

    public String getRootDecisionInstanceId() {
        return rootDecisionInstanceId;
    }

    public void setRootDecisionInstanceId(String rootDecisionInstanceId) {
        this.rootDecisionInstanceId = rootDecisionInstanceId;
    }

    public String getRootProcessInstanceId() {
        return rootProcessInstanceId;
    }

    public void setRootProcessInstanceId(String rootProcessInstanceId) {
        this.rootProcessInstanceId = rootProcessInstanceId;
    }

    public String getDecisionRequirementsDefinitionId() {
        return decisionRequirementsDefinitionId;
    }

    public void setDecisionRequirementsDefinitionId(String decisionRequirementsDefinitionId) {
        this.decisionRequirementsDefinitionId = decisionRequirementsDefinitionId;
    }

    public String getDecisionRequirementsDefinitionKey() {
        return decisionRequirementsDefinitionKey;
    }

    public void setDecisionRequirementsDefinitionKey(String decisionRequirementsDefinitionKey) {
        this.decisionRequirementsDefinitionKey = decisionRequirementsDefinitionKey;
    }

    @Override
    public String toString() {
        return "GetHistoricDecisionInstanceResponse{" +
                "id='" + id + '\'' +
                ", decisionDefinitionId='" + decisionDefinitionId + '\'' +
                ", decisionDefinitionKey='" + decisionDefinitionKey + '\'' +
                ", decisionDefinitionName='" + decisionDefinitionName + '\'' +
                ", evaluationTime='" + evaluationTime + '\'' +
                ", removalTime='" + removalTime + '\'' +
                ", processDefinitionId='" + processDefinitionId + '\'' +
                ", processDefinitionKey='" + processDefinitionKey + '\'' +
                ", processInstanceId='" + processInstanceId + '\'' +
                ", caseDefinitionId='" + caseDefinitionId + '\'' +
                ", caseDefinitionKey='" + caseDefinitionKey + '\'' +
                ", caseInstanceId='" + caseInstanceId + '\'' +
                ", activityId='" + activityId + '\'' +
                ", activityInstanceId='" + activityInstanceId + '\'' +
                ", tenantId='" + tenantId + '\'' +
                ", userId='" + userId + '\'' +
                ", inputs='" + inputs + '\'' +
                ", outputs='" + outputs + '\'' +
                ", collectResultValue='" + collectResultValue + '\'' +
                ", rootDecisionInstanceId='" + rootDecisionInstanceId + '\'' +
                ", rootProcessInstanceId='" + rootProcessInstanceId + '\'' +
                ", decisionRequirementsDefinitionId='" + decisionRequirementsDefinitionId + '\'' +
                ", decisionRequirementsDefinitionKey='" + decisionRequirementsDefinitionKey + '\'' +
                '}';
    }
}
