// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Response structure of Camunda REST API <code>GET /process-definition</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetProcessDefinitionResponse {
    private String id;
    private String key;
    private String category;
    private String description;
    private String name;
    private Integer version;
    private String resource;
    private String deploymentId;
    private String diagram;
    private Boolean suspended;
    private String tenantId;
    private String versionTag;
    private Integer historyTimeToLive;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getKey() {
        return this.key;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getVersion() {
        return this.version;
    }

    @java.lang.SuppressWarnings("all")
    public String getResource() {
        return this.resource;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeploymentId() {
        return this.deploymentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDiagram() {
        return this.diagram;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getSuspended() {
        return this.suspended;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public String getVersionTag() {
        return this.versionTag;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHistoryTimeToLive() {
        return this.historyTimeToLive;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setKey(final String key) {
        this.key = key;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setVersion(final Integer version) {
        this.version = version;
    }

    @java.lang.SuppressWarnings("all")
    public void setResource(final String resource) {
        this.resource = resource;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeploymentId(final String deploymentId) {
        this.deploymentId = deploymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDiagram(final String diagram) {
        this.diagram = diagram;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuspended(final Boolean suspended) {
        this.suspended = suspended;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setVersionTag(final String versionTag) {
        this.versionTag = versionTag;
    }

    @java.lang.SuppressWarnings("all")
    public void setHistoryTimeToLive(final Integer historyTimeToLive) {
        this.historyTimeToLive = historyTimeToLive;
    }
}
