// Generated by delombok at Fri Jan 04 11:18:40 CET 2019
package de.viadee.camunda.kafka.pollingclient.service.polling.rest.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Response structure of Camunda REST API <code>GET /process-definition/123/xml</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetProcessDefinitionXmlResponse {

    private String id;
    private String bpmn20Xml;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getBpmn20Xml() {
        return this.bpmn20Xml;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setBpmn20Xml(final String bpmn20Xml) {
        this.bpmn20Xml = bpmn20Xml;
    }
}
