// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

import java.util.Date;

/**
 * <p>
 * DeploymentEvent class.
 * </p>
 *
 *
 *
 * @author viadee
 *
 * @version $Id: $Id
 */
public class DeploymentEvent {

    private String id;
    private String deploymentId;
    private String name;
    private String source;
    private Date deploymentTime;
    private String tenantId;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeploymentId() {
        return this.deploymentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getSource() {
        return this.source;
    }

    @java.lang.SuppressWarnings("all")
    public Date getDeploymentTime() {
        return this.deploymentTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeploymentId(final String deploymentId) {
        this.deploymentId = deploymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setSource(final String source) {
        this.source = source;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeploymentTime(final Date deploymentTime) {
        this.deploymentTime = deploymentTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }
}
