// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

import java.util.Date;

/**
 * <p>
 * DetailEvent class.
 * </p>
 *
 * 
 * 
 * @author viadee
 * 
 * @version $Id: $Id
 */
public class DetailEvent extends HistoryEvent {

    private String activityInstanceId;
    private String taskId;
    private Date timestamp;
    private String tenantId;
    private String userOperationId;

    @java.lang.SuppressWarnings("all")
    public String getActivityInstanceId() {
        return this.activityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTaskId() {
        return this.taskId;
    }

    @java.lang.SuppressWarnings("all")
    public Date getTimestamp() {
        return this.timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserOperationId() {
        return this.userOperationId;
    }

    @java.lang.SuppressWarnings("all")
    public void setActivityInstanceId(final String activityInstanceId) {
        this.activityInstanceId = activityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTaskId(final String taskId) {
        this.taskId = taskId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimestamp(final Date timestamp) {
        this.timestamp = timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserOperationId(final String userOperationId) {
        this.userOperationId = userOperationId;
    }
}
