// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * <p>
 * HistoryEvent class.
 * </p>
 *
 *
 *
 * @author viadee
 *
 * @version $Id: $Id
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class HistoryEvent {

    private String id;
    private String processInstanceId;
    private String executionId;
    private String processDefinitionId;
    private String processDefinitionKey;
    private String processDefinitionName;
    private Integer processDefinitionVersion;
    private String caseInstanceId;
    private String caseExecutionId;
    private String caseDefinitionId;
    private String caseDefinitionKey;
    private String caseDefinitionName;
    private String eventType;
    private long sequenceCounter;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getExecutionId() {
        return this.executionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionKey() {
        return this.processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionName() {
        return this.processDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getProcessDefinitionVersion() {
        return this.processDefinitionVersion;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseInstanceId() {
        return this.caseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseExecutionId() {
        return this.caseExecutionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseDefinitionId() {
        return this.caseDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseDefinitionKey() {
        return this.caseDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getCaseDefinitionName() {
        return this.caseDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public String getEventType() {
        return this.eventType;
    }

    @java.lang.SuppressWarnings("all")
    public long getSequenceCounter() {
        return this.sequenceCounter;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessInstanceId(final String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setExecutionId(final String executionId) {
        this.executionId = executionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionId(final String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionKey(final String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionName(final String processDefinitionName) {
        this.processDefinitionName = processDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionVersion(final Integer processDefinitionVersion) {
        this.processDefinitionVersion = processDefinitionVersion;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseInstanceId(final String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseExecutionId(final String caseExecutionId) {
        this.caseExecutionId = caseExecutionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseDefinitionId(final String caseDefinitionId) {
        this.caseDefinitionId = caseDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseDefinitionKey(final String caseDefinitionKey) {
        this.caseDefinitionKey = caseDefinitionKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setCaseDefinitionName(final String caseDefinitionName) {
        this.caseDefinitionName = caseDefinitionName;
    }

    @java.lang.SuppressWarnings("all")
    public void setEventType(final String eventType) {
        this.eventType = eventType;
    }

    @java.lang.SuppressWarnings("all")
    public void setSequenceCounter(final long sequenceCounter) {
        this.sequenceCounter = sequenceCounter;
    }
}
