// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

import java.util.Date;

/**
 * <p>
 * IncidentEvent class.
 * </p>
 *
 * 
 * 
 * @author viadee
 * 
 * @version $Id: $Id
 */
public class IncidentEvent extends HistoryEvent {

    private Date createTime;
    private Date endTime;
    private String incidentType;
    private String activityId;
    private String causeIncidentId;
    private String rootCauseIncidentId;
    private String configuration;
    private String incidentMessage;
    private int incidentState;
    private String tenantId;
    private String jobDefinitionId;

    @java.lang.SuppressWarnings("all")
    public Date getCreateTime() {
        return this.createTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getIncidentType() {
        return this.incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public String getActivityId() {
        return this.activityId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCauseIncidentId() {
        return this.causeIncidentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRootCauseIncidentId() {
        return this.rootCauseIncidentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getConfiguration() {
        return this.configuration;
    }

    @java.lang.SuppressWarnings("all")
    public String getIncidentMessage() {
        return this.incidentMessage;
    }

    @java.lang.SuppressWarnings("all")
    public int getIncidentState() {
        return this.incidentState;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public String getJobDefinitionId() {
        return this.jobDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreateTime(final Date createTime) {
        this.createTime = createTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndTime(final Date endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentType(final String incidentType) {
        this.incidentType = incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public void setActivityId(final String activityId) {
        this.activityId = activityId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCauseIncidentId(final String causeIncidentId) {
        this.causeIncidentId = causeIncidentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRootCauseIncidentId(final String rootCauseIncidentId) {
        this.rootCauseIncidentId = rootCauseIncidentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setConfiguration(final String configuration) {
        this.configuration = configuration;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentMessage(final String incidentMessage) {
        this.incidentMessage = incidentMessage;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentState(final int incidentState) {
        this.incidentState = incidentState;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setJobDefinitionId(final String jobDefinitionId) {
        this.jobDefinitionId = jobDefinitionId;
    }
}
