// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

/**
 * <p>ProcessInstanceEvent class.</p>
 *
 * @author viadee
 * @version $Id: $Id
 */
public class ProcessInstanceEvent extends ScopeInstanceEvent {
    private String businessKey;
    private String startUserId;
    private String superProcessInstanceId;
    private String superCaseInstanceId;
    private String deleteReason;
    private String endActivityId;
    private String startActivityId;
    private String tenantId;
    private String state;

    @java.lang.SuppressWarnings("all")
    public String getBusinessKey() {
        return this.businessKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartUserId() {
        return this.startUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSuperProcessInstanceId() {
        return this.superProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSuperCaseInstanceId() {
        return this.superCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeleteReason() {
        return this.deleteReason;
    }

    @java.lang.SuppressWarnings("all")
    public String getEndActivityId() {
        return this.endActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartActivityId() {
        return this.startActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTenantId() {
        return this.tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public void setBusinessKey(final String businessKey) {
        this.businessKey = businessKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartUserId(final String startUserId) {
        this.startUserId = startUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuperProcessInstanceId(final String superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuperCaseInstanceId(final String superCaseInstanceId) {
        this.superCaseInstanceId = superCaseInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeleteReason(final String deleteReason) {
        this.deleteReason = deleteReason;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndActivityId(final String endActivityId) {
        this.endActivityId = endActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartActivityId(final String startActivityId) {
        this.startActivityId = startActivityId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTenantId(final String tenantId) {
        this.tenantId = tenantId;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }
}
