// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

import java.util.Date;

/**
 * <p>ScopeInstanceEvent class.</p>
 *
 * @author viadee
 * @version $Id: $Id
 */
public class ScopeInstanceEvent extends HistoryEvent {
    private Long durationInMillis;
    private Date startTime;
    private Date endTime;

    @java.lang.SuppressWarnings("all")
    public Long getDurationInMillis() {
        return this.durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public Date getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setDurationInMillis(final Long durationInMillis) {
        this.durationInMillis = durationInMillis;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartTime(final Date startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndTime(final Date endTime) {
        this.endTime = endTime;
    }
}
