// Generated by delombok at Wed Jan 09 13:24:24 CET 2019
package de.viadee.camunda.kafka.event;

/**
 * <p>
 * VariableUpdateEvent class.
 * </p>
 *
 * 
 * 
 * @author viadee
 * 
 * @version $Id: $Id
 */
public class VariableUpdateEvent extends DetailEvent {

    private int revision;
    private String variableName;
    private String variableInstanceId;
    private String scopeActivityInstanceId;
    private String serializerName;
    private Long longValue;
    private Double doubleValue;
    private String textValue;
    private Object complexValue;

    @java.lang.SuppressWarnings("all")
    public int getRevision() {
        return this.revision;
    }

    @java.lang.SuppressWarnings("all")
    public String getVariableName() {
        return this.variableName;
    }

    @java.lang.SuppressWarnings("all")
    public String getVariableInstanceId() {
        return this.variableInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getScopeActivityInstanceId() {
        return this.scopeActivityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSerializerName() {
        return this.serializerName;
    }

    @java.lang.SuppressWarnings("all")
    public Long getLongValue() {
        return this.longValue;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDoubleValue() {
        return this.doubleValue;
    }

    @java.lang.SuppressWarnings("all")
    public String getTextValue() {
        return this.textValue;
    }

    @java.lang.SuppressWarnings("all")
    public Object getComplexValue() {
        return this.complexValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setRevision(final int revision) {
        this.revision = revision;
    }

    @java.lang.SuppressWarnings("all")
    public void setVariableName(final String variableName) {
        this.variableName = variableName;
    }

    @java.lang.SuppressWarnings("all")
    public void setVariableInstanceId(final String variableInstanceId) {
        this.variableInstanceId = variableInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setScopeActivityInstanceId(final String scopeActivityInstanceId) {
        this.scopeActivityInstanceId = scopeActivityInstanceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSerializerName(final String serializerName) {
        this.serializerName = serializerName;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongValue(final Long longValue) {
        this.longValue = longValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoubleValue(final Double doubleValue) {
        this.doubleValue = doubleValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setTextValue(final String textValue) {
        this.textValue = textValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setComplexValue(final Object complexValue) {
        this.complexValue = complexValue;
    }
}
